language: java
jdk:
  - openjdk8
services:
  - docker
#before_script: pip install docker-compose
before_install:
  - docker pull openjdk:8-jdk-alpine

# Test & Build SpringBoot app
script:
  - cd /manager-api
  - ./gradlew build
  - cd ..

# Create Docker image for our app and push it to Dockerhub 
after_success:
  - if [[ "$TRAVIS_BRANCH" == "aws_deployment" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker-compose build ;
      docker tag game-api $DOCKER_USERNAME/game-api ;
      docker tag manager-api $DOCKER_USERNAME/manager-api ;
      docker tag season-api $DOCKER_USERNAME/season-api ;
      
      docker push $DOCKER_USERNAME/game-api ;
      docker push $DOCKER_USERNAME/manager-api ;
      docker push $DOCKER_USERNAME/season-api ;
    fi

# Allow Travis to help deploy the app on AWS elasticbeanstalk
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: container-sample
  env: Containersample-env
  bucket-name: elasticbeanstalk-us-east-1-669582617787
  bucket-path: container-sample
  on:
    branch: aws_deployment
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY